---
ID: "b1d445b4-ebf2-4e57-b53a-45ab0f7e794e"
Parent: "c626493f-1cc3-4986-a701-f28b83d649f7"
Template: "1404a77a-d5fd-46b3-aa4c-200f3d519979"
Path: /sitecore/system/Modules/Layout Service/Rendering Contents Resolvers/ProductsRH
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200729T192823Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c3d7035b-28f7-4c54-9135-05a1ed8b1d48"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210408T095512Z
