---
ID: "523c22f8-c5ea-4b10-ac1e-c339b71124a1"
Parent: "10bd1f3e-2160-4f71-8b90-cf9c75d0b254"
Template: "10bd1f3e-2160-4f71-8b90-cf9c75d0b254"
Path: /sitecore/templates/Feature/BasicRH/Accordion Item Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{87C8200F-A0BA-4EA8-AB7C-558D885BFEBA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190507T160837Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
          sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "23b1daff-3341-4fdc-9b41-e5d1cda1995a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
          sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190930T183114Z
