---
ID: "9f514e79-d926-48d1-a8b9-e1b606e2cbe9"
Parent: "cfbeadf2-8657-4fda-9a9a-6929ffb05cc1"
Template: "cfbeadf2-8657-4fda-9a9a-6929ffb05cc1"
Path: /sitecore/templates/Feature/ServicesRH/Testimonial Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {BCF7B1AB-02CE-4B43-BB00-99AA5685094B}
    {CFBEADF2-8657-4FDA-9A9A-6929FFB05CC1}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190507T141235Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
          sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3ac79faf-5bf2-4e5a-9ed4-aa846eadc70f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
          sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190930T183108Z
